# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93836a001e3b17bee90d43f3cf09b6985e27bbaa40745eaa9d7e63d4e5f47f1d0795a9310663fdc797501f2874b43ed5c6afdc1709e195477cdbd46601afa56a

test:
  secret_key_base: 103427a3d7299faf578ff03d0db5a76dfb49329ea5c734c1fe518afd5e7a40c1a44b25ea43fb4853e015c07dfd4d7b0b79d6c2a931ca6ad6bcf41eebe4f73160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
